proteins:
  - XPD_P18074
  - XPF_Q92889
  - XPC_Q01831
  - XPB_P19447
  - CSB_Q03468
  - CSA_Q13216
  - DDB2_Q92466
  - STK19_P49842
  - UVSSA_Q2YD98
  - XPA_P23025
  
# Paths to databases
blast_database: "/cta/users/mmalkoc/evo_of_RPs/blastDB/eu_blastDB"
blastdb_fasta: "/cta/users/mmalkoc/evo_of_RPs/initial_data/proteomes/proteomes_subset.fasta"

# Additional parameters
given_taxid: "9606"

