jobs: 100

executor: "cluster-generic"
cluster-generic-submit-cmd: "bash workflows/scripts/submit_slurm.sh \
                              {resources.account} \
                              {rule} \
                              {resources.protein_name} \
                              {resources.partition} \
                              {resources.qos} \
                              {resources.cpus} \
                              {resources.mem_gb}"
                              

software-deployment-method: "conda"

printshellcmds: True
keep-going: True
rerun-incomplete: True
max-jobs-per-second: 2
max-status-checks-per-second: 2
latency-wait: 60
rerun-triggers: "mtime"

default-resources:
  account: adelab
  partition: genomics
  qos: adelab
  cpus: 1
  mem_gb: 8
  protein_name: 'NA'

set-resources:
  hmmpress:
    partition: genomics
    qos: adelab
    cpus: 4
    mem_gb: 40

  make_blasDB:
    partition: genomics
    qos: adelab
    cpus: 4
    mem_gb: 50

  psiblast:
    partition: genomics
    qos: adelab
    cpus: 4
    mem_gb: 8

  parse_psiblast:
    partition: genomics
    qos: adelab
    mem_gb: 50

  mafft_einsi:
    partition: genomics
    qos: adelab
    cpus: 24
    mem_gb: 300

  clipkit:
    partition: genomics
    qos: adelab
    cpus: 4
    mem_gb: 40

  modelfinder:
    partition: genomics
    qos: adelab
    cpus: 20
    mem_gb: 80

  parse_modelfinder_output:
    partition: genomics
    qos: adelab
    cpus: 1
    mem_gb: 4

  iqtree:
    partition: genomics
    qos: adelab
    #cpus: 16  #<-- Commented out to allow dynamic assignment from iqtree.smk
    mem_gb: 60 #<-- Commented out to allow dynamic assignment from iqtree.smk

  hmmscan:
    partition: genomics
    qos: adelab
    cpus: 8
    mem_gb: 20

  download_pfamDB:
    partition: genomics
    qos: adelab
    mem_gb: 20

  combine_figures:
    mem_gb: 40