jobs: 100

executor: "cluster-generic"
cluster-generic-submit-cmd: "bash workflows/scripts/submit_slurm.sh \
                              {resources.account} \
                              {rule} \
                              {resources.protein_name} \
                              {resources.partition} \
                              {resources.qos} \
                              {resources.cpus} \
                              {resources.mem_gb}"
                              

software-deployment-method: "conda"

printshellcmds: True
keep-going:     True
rerun-incomplete: True
#rerun-triggers: "mtime"

default-resources:
  account: investor
  partition: short_investor
  qos: short_investor
  cpus: 1
  mem_gb: 8
  protein_name: 'NA'

set-resources:
  hmmpress:
    partition: mid_investor
    qos: mid_investor
    cpus: 4
    mem_gb: 40

  make_blasDB:
    partition: mid_investor
    qos: mid_investor
    cpus: 4
    mem_gb: 50

  psiblast:
    partition: mid_investor
    qos: mid_investor
    cpus: 4
    mem_gb: 8

  parse_psiblast:
    partition: mid_investor
    qos: mid_investor
    mem_gb: 50

  mafft_fftns:
    partition: long_investor
    qos: long_investor
    cpus: 10
    mem_gb: 100

  clipkit_fftns:
    partition: mid_investor
    qos: mid_investor
    cpus: 4
    mem_gb: 16

  iqtree:
    partition: longer_investor
    qos: longer_investor
    cpus: 10
    mem_gb: 20

  hmmscan:
    partition: mid_investor
    qos: mid_investor
    cpus: 8
    mem_gb: 10

  download_pfamDB:
    partition: mid_investor
    qos: mid_investor
    mem_gb: 20

  combine_figures:
    mem_gb: 40