proteins:
  #- ERCC2_P18074
  #- XPF_Q92889
  #- XPC_Q01831
  #- ERCC3_P19447
  #- ERCC6_Q03468
  #- ERCC8_Q13216
  #- DDB2_Q92466
  #- STK19_P49842
  #- UVSSA_Q2YD98
  - XPA_P23025
  
# Paths to databases
blast_database: "resources/blastDB/eu_blastDB"
blastdb_fasta: "resources/proteomes/proteomes_subset.fasta"
pfamDB: "/cta/users/mmalkoc/evo_of_RPs/domain_architecture/Pfam-A.hmm"

# Additional parameters
given_taxid: "9606"

