proteins:
  #- ERCC2_P18074
  #- Q92889
  #- XPC_Q01831
  #- ERCC3_P19447
  #- ERCC6_Q03468
  #- ERCC8_Q13216
  #- DDB2_Q92466
  - P49842
  #- UVSSA_Q2YD98
  - P23025
  
# Paths to databases and files
allProteomesFasta: "resources/proteomes/proteomes_subset.fasta"

# URLs
pfamDB_URL: "https://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz"
md5_URL: "https://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/md5_checksums"

# Taxonomy ID of the target species/organism
subject_taxid: "9606"  # Homo sapiens

