proteins:
  - P49842
  - Q8TAQ2
  - Q9UGP5
  - P49916
  - Q8WUZ0
  - P60709
  - Q8NHY5


  
# Paths to databases and files
allProteomesFasta: "resources/proteomes/compiled_subset.faa"

# URLs
pfamDB_URL: "http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz"
md5_URL: "http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/md5_checksums"

# Taxonomy ID of the target species/organism
subject_taxid: "9606"  # Homo sapiens